version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - pip install -r "Search Function/requirements.txt" -t "Search Function"/    
      - aws cloudformation package --template-file "Search Function/search-gateway.yaml" --s3-bucket codepipeline-us-east-1-66843b3dcf90-47f6-a5e2-120b13d644c9 --output-template-file gateway.yaml

artifacts:
  type: zip
  files:
    - search-gateway.yaml
    - gateway.yaml