AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  pdftotxt:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: pdftotxt
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 900
      Role: 'arn:aws:iam::122118540225:role/search-engine-lambda-role'
      Environment:
        Variables:
          TARGET_BUCKET: inter-docu-store-09052026093405
